package services

import (
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/jj.jobo/FGC/internal/dto"
	"github.com/jung-kurt/gofpdf"
)

type ReportPDFService struct {
	outputDirectory string
}

func NewReportPDFService(
	outputDirectory string,
) *ReportPDFService {
	return &ReportPDFService{
		outputDirectory: outputDirectory,
	}
}

func (s *ReportPDFService) GenerateCollectionReport(
	data *dto.CollectionReportData,
	dateFrom string,
	dateTo string,
) (string, error) {

	if err := os.MkdirAll(
		s.outputDirectory,
		0755,
	); err != nil {
		return "", err
	}

	pdf := gofpdf.New(
		"L",
		"mm",
		"A4",
		"",
	)

	pdf.SetTitle(
		"Summary of Collection",
		true,
	)

	pdf.SetAuthor(
		"FGC",
		true,
	)

	pdf.SetMargins(
		10,
		10,
		10,
	)

	pdf.SetAutoPageBreak(
		true,
		15,
	)

	pdf.SetFooterFunc(
		func() {

			pdf.SetY(-12)

			pdf.SetFont(
				"Arial",
				"",
				7,
			)

			pdf.CellFormat(
				0,
				5,
				"Generated by FGC",
				"",
				0,
				"L",
				false,
				0,
				"",
			)

			pdf.CellFormat(
				0,
				5,
				fmt.Sprintf(
					"Page %d",
					pdf.PageNo(),
				),
				"",
				0,
				"R",
				false,
				0,
				"",
			)
		},
	)

	pdf.AddPage()

	drawCollectionHeader(
		pdf,
		dateFrom,
		dateTo,
	)

	drawCollectionSummary(
		pdf,
		data.Summary,
	)

	pdf.Ln(5)

	drawCollectionTable(
		pdf,
		data.Rows,
	)

	// drawCollectionFooter(
	// 	pdf,
	// )

	filename := fmt.Sprintf(
		"summary_collection_%s.pdf",
		time.Now().Format(
			"20060102_150405",
		),
	)

	path := filepath.Join(
		s.outputDirectory,
		filename,
	)

	if err := pdf.OutputFileAndClose(
		path,
	); err != nil {
		return "", err
	}

	return path, nil
}

func drawCollectionHeader(
	pdf *gofpdf.Fpdf,
	dateFrom string,
	dateTo string,
) {

	pdf.SetFont(
		"Arial",
		"B",
		18,
	)

	pdf.CellFormat(
		0,
		8,
		"FGC",
		"",
		1,
		"C",
		false,
		0,
		"",
	)

	pdf.SetFont(
		"Arial",
		"B",
		14,
	)

	pdf.CellFormat(
		0,
		8,
		"SUMMARY OF COLLECTION",
		"",
		1,
		"C",
		false,
		0,
		"",
	)

	pdf.SetFont(
		"Arial",
		"",
		9,
	)

	pdf.CellFormat(
		0,
		6,
		fmt.Sprintf(
			"Reporting Period: %s to %s",
			dateFrom,
			dateTo,
		),
		"",
		1,
		"C",
		false,
		0,
		"",
	)

	pdf.CellFormat(
		0,
		6,
		fmt.Sprintf(
			"Generated: %s",
			time.Now().Format(
				"January 02, 2006 03:04 PM",
			),
		),
		"",
		1,
		"C",
		false,
		0,
		"",
	)

	pdf.Ln(4)

	pdf.Line(
		10,
		pdf.GetY(),
		200,
		pdf.GetY(),
	)

	pdf.Ln(5)
}

func drawCollectionSummary(
	pdf *gofpdf.Fpdf,
	summary dto.CollectionReportSummary,
) {

	pdf.SetFont(
		"Arial",
		"B",
		10,
	)

	pdf.CellFormat(
		0,
		7,
		"COLLECTION SUMMARY",
		"",
		1,
		"L",
		false,
		0,
		"",
	)

	pdf.Ln(3)

	// Landscape A4:
	// 297mm width
	// 10mm margins
	// 277mm usable width

	cardWidth := 64.0
	cardHeight := 22.0
	gap := 6.0

	startX := 10.0
	startY := pdf.GetY()

	cards := []struct {
		title string
		value string
	}{
		{
			title: "Transactions",
			value: fmt.Sprintf(
				"%d",
				summary.TotalTransactions,
			),
		},
		{
			title: "Principal",
			value: formatPHP(
				summary.TotalPrincipal,
			),
		},
		{
			title: "Interest",
			value: formatPHP(
				summary.TotalInterest,
			),
		},
		{
			title: "Total Collection",
			value: formatPHP(
				summary.TotalCollection,
			),
		},
	}

	for i, card := range cards {

		x := startX +
			float64(i)*
				(cardWidth+gap)

		// Card border
		pdf.Rect(
			x,
			startY,
			cardWidth,
			cardHeight,
			"D",
		)

		// Title
		pdf.SetXY(
			x,
			startY+3,
		)

		pdf.SetFont(
			"Arial",
			"",
			8,
		)

		pdf.CellFormat(
			cardWidth,
			5,
			card.title,
			"",
			0,
			"C",
			false,
			0,
			"",
		)

		// Value
		pdf.SetXY(
			x,
			startY+10,
		)

		pdf.SetFont(
			"Arial",
			"B",
			11,
		)

		pdf.CellFormat(
			cardWidth,
			7,
			card.value,
			"",
			0,
			"C",
			false,
			0,
			"",
		)
	}

	pdf.SetY(
		startY + cardHeight + 6,
	)
}

func drawCollectionTable(
	pdf *gofpdf.Fpdf,
	rows []dto.CollectionReportRow,
) {

	pdf.SetFont(
		"Arial",
		"B",
		10,
	)

	pdf.CellFormat(
		0,
		7,
		"COLLECTION DETAILS",
		"",
		1,
		"L",
		false,
		0,
		"",
	)

	pdf.Ln(2)

	headers := []string{
		"Date",
		"Reference",
		"PN Number",
		"Client",
		"Principal",
		"Interest",
		"Amount Paid",
		"Channel",
	}

	widths := []float64{
		22,
		30,
		30,
		55,
		30,
		30,
		32,
		28,
	}

	// Total = 257mm
	// Landscape A4 usable width = 277mm

	drawHeader := func() {

		pdf.SetFont(
			"Arial",
			"B",
			7,
		)

		for i, header := range headers {

			pdf.CellFormat(
				widths[i],
				8,
				header,
				"1",
				0,
				"C",
				false,
				0,
				"",
			)
		}

		pdf.Ln(-1)
	}

	drawHeader()

	pdf.SetFont(
		"Arial",
		"",
		7,
	)

	for _, row := range rows {

		values := []string{
			row.PaymentDate,
			row.ReferenceNumber,
			row.PNNumber,
			row.ClientName,
			formatPHP(
				row.PrincipalApplied,
			),
			formatPHP(
				row.InterestApplied,
			),
			formatPHP(
				row.AmountPaid,
			),
			row.PaymentChannel,
		}

		for i, value := range values {

			align := "L"

			if i >= 4 && i <= 6 {
				align = "R"
			}

			pdf.CellFormat(
				widths[i],
				7,
				value,
				"1",
				0,
				align,
				false,
				0,
				"",
			)
		}

		pdf.Ln(-1)
	}

	// ========================================
	// TOTAL
	// ========================================

	var principal float64
	var interest float64
	var collection float64

	for _, row := range rows {

		principal +=
			row.PrincipalApplied

		interest +=
			row.InterestApplied

		collection +=
			row.AmountPaid
	}

	pdf.SetFont(
		"Arial",
		"B",
		7,
	)

	labelWidth :=
		widths[0] +
			widths[1] +
			widths[2] +
			widths[3]

	pdf.CellFormat(
		labelWidth,
		8,
		"TOTAL",
		"1",
		0,
		"R",
		false,
		0,
		"",
	)

	pdf.CellFormat(
		widths[4],
		8,
		formatPHP(principal),
		"1",
		0,
		"R",
		false,
		0,
		"",
	)

	pdf.CellFormat(
		widths[5],
		8,
		formatPHP(interest),
		"1",
		0,
		"R",
		false,
		0,
		"",
	)

	pdf.CellFormat(
		widths[6],
		8,
		formatPHP(collection),
		"1",
		0,
		"R",
		false,
		0,
		"",
	)

	pdf.CellFormat(
		widths[7],
		8,
		"",
		"1",
		0,
		"L",
		false,
		0,
		"",
	)

	pdf.Ln(-1)

}

// func drawCollectionFooter(
// 	pdf *gofpdf.Fpdf,
// ) {

// 	pdf.SetY(-15)

// 	pdf.SetFont(
// 		"Arial",
// 		"",
// 		7,
// 	)

// 	pdf.CellFormat(
// 		0,
// 		5,
// 		"Generated by FGC",
// 		"",
// 		0,
// 		"L",
// 		false,
// 		0,
// 		"",
// 	)

// 	pdf.CellFormat(
// 		0,
// 		5,
// 		fmt.Sprintf(
// 			"Page %d",
// 			pdf.PageNo(),
// 		),
// 		"",
// 		0,
// 		"R",
// 		false,
// 		0,
// 		"",
// 	)
// }

func formatPHP(
	value float64,
) string {

	return fmt.Sprintf(
		"PHP %.2f",
		value,
	)
}

func (s *ReportPDFService) GenerateAmortizationReport(
	data *dto.AmortizationReportData,
) (string, error) {

	if data == nil || len(data.Rows) == 0 {
		return "", fmt.Errorf(
			"no amortization data available",
		)
	}

	if err := os.MkdirAll(
		s.outputDirectory,
		0755,
	); err != nil {
		return "", err
	}

	pdf := gofpdf.New(
		"L",
		"mm",
		"A4",
		"",
	)

	pdf.SetTitle(
		"Loan Account Amortization",
		true,
	)

	pdf.SetAuthor(
		"FGC",
		true,
	)

	pdf.SetMargins(
		10,
		10,
		10,
	)

	pdf.SetAutoPageBreak(
		true,
		15,
	)

	pdf.SetFooterFunc(
		func() {

			pdf.SetY(-12)

			pdf.SetFont(
				"Arial",
				"",
				7,
			)

			pdf.CellFormat(
				0,
				5,
				"Generated by FGC",
				"",
				0,
				"L",
				false,
				0,
				"",
			)

			pdf.CellFormat(
				0,
				5,
				fmt.Sprintf(
					"Page %d",
					pdf.PageNo(),
				),
				"",
				0,
				"R",
				false,
				0,
				"",
			)
		},
	)

	pdf.AddPage()

	drawAmortizationHeader(
		pdf,
		data.Loan,
	)

	drawLoanInformation(
		pdf,
		data.Loan,
	)

	drawAmortizationSummary(
		pdf,
		data.Summary,
	)

	pdf.AddPage()

	drawAmortizationTable(
		pdf,
		data.Rows,
		data.Summary,
	)

	filename := fmt.Sprintf(
		"loan_amortization_%s_%s.pdf",
		data.Loan.PNNumber,
		time.Now().Format(
			"20060102_150405",
		),
	)

	path := filepath.Join(
		s.outputDirectory,
		filename,
	)

	if err := pdf.OutputFileAndClose(
		path,
	); err != nil {
		return "", err
	}

	return path, nil
}

func drawAmortizationHeader(
	pdf *gofpdf.Fpdf,
	loan dto.AmortizationReportRow,
) {

	pdf.SetFont(
		"Arial",
		"B",
		18,
	)

	pdf.CellFormat(
		0,
		8,
		"FGC",
		"",
		1,
		"C",
		false,
		0,
		"",
	)

	pdf.SetFont(
		"Arial",
		"B",
		14,
	)

	pdf.CellFormat(
		0,
		8,
		"LOAN ACCOUNT AMORTIZATION",
		"",
		1,
		"C",
		false,
		0,
		"",
	)

	pdf.SetFont(
		"Arial",
		"",
		9,
	)

	pdf.CellFormat(
		0,
		6,
		fmt.Sprintf(
			"PN Number: %s",
			loan.PNNumber,
		),
		"",
		1,
		"C",
		false,
		0,
		"",
	)

	pdf.CellFormat(
		0,
		6,
		fmt.Sprintf(
			"Generated: %s",
			time.Now().Format(
				"January 02, 2006 03:04 PM",
			),
		),
		"",
		1,
		"C",
		false,
		0,
		"",
	)

	pdf.Ln(4)

	pdf.Line(
		10,
		pdf.GetY(),
		287,
		pdf.GetY(),
	)

	pdf.Ln(5)
}

func drawLoanInformation(
	pdf *gofpdf.Fpdf,
	loan dto.AmortizationReportRow,
) {
	pdf.SetFont(
		"Arial",
		"B",
		10,
	)

	pdf.CellFormat(
		0,
		7,
		"LOAN INFORMATION",
		"",
		1,
		"L",
		false,
		0,
		"",
	)

	pdf.Ln(2)

	// ========================================
	// FIXED 4-COLUMN GRID
	// ========================================

	cellWidth := 68.0
	labelHeight := 6.0
	valueHeight := 8.0
	rowHeight := labelHeight + valueHeight

	fields := []struct {
		label string
		value string
	}{
		{
			"Client",
			loan.ClientName,
		},
		{
			"Contact",
			loan.ContactNumber,
		},
		{
			"PN Number",
			loan.PNNumber,
		},
		{
			"Loan Type",
			loan.LoanType,
		},

		{
			"Principal",
			formatPHP(
				loan.PrincipalAmount,
			),
		},
		{
			"Interest Rate",
			fmt.Sprintf(
				"%.2f%%",
				loan.InterestRate,
			),
		},
		{
			"Loan Interest",
			formatPHP(
				loan.LoanInterest,
			),
		},
		{
			"PN Value",
			formatPHP(
				loan.PNValue,
			),
		},

		{
			"Loan Term",
			fmt.Sprintf(
				"%d",
				loan.LoanTerm,
			),
		},
		{
			"Frequency",
			loan.Frequency,
		},
		{
			"Amortization",
			formatPHP(
				loan.AmortizationAmount,
			),
		},
		{
			"Status",
			loan.LoanStatus,
		},

		{
			"Disbursement Date",
			loan.DisbursementDate,
		},
		{
			"Maturity Date",
			loan.MaturityDate,
		},
	}

	startX := 10.0
	startY := pdf.GetY()

	for i, field := range fields {

		row := i / 4
		col := i % 4

		x := startX +
			float64(col)*cellWidth

		y := startY +
			float64(row)*rowHeight

		// ========================================
		// LABEL
		// ========================================

		pdf.SetXY(
			x,
			y,
		)

		pdf.SetFont(
			"Arial",
			"B",
			7,
		)

		pdf.CellFormat(
			cellWidth,
			labelHeight,
			field.label,
			"1",
			0,
			"L",
			false,
			0,
			"",
		)

		// ========================================
		// VALUE
		// ========================================

		pdf.SetXY(
			x,
			y+labelHeight,
		)

		pdf.SetFont(
			"Arial",
			"",
			8,
		)

		pdf.CellFormat(
			cellWidth,
			valueHeight,
			field.value,
			"1",
			0,
			"L",
			false,
			0,
			"",
		)
	}

	// ========================================
	// MOVE CURSOR BELOW ENTIRE GRID
	// ========================================

	// totalRows := int(
	// 	math.Ceil(
	// 		float64(len(fields)) / 4,
	// 	),
	// )

	pdf.SetY(
		startY +
			(4 * rowHeight) +
			5,
	)
}

func drawAmortizationSummary(
	pdf *gofpdf.Fpdf,
	summary dto.AmortizationReportSummary,
) {
	pdf.Ln(4)

	pdf.SetFont(
		"Arial",
		"B",
		10,
	)

	pdf.CellFormat(
		0,
		7,
		"ACCOUNT SUMMARY",
		"",
		1,
		"L",
		false,
		0,
		"",
	)

	pdf.Ln(2)

	items := []struct {
		title string
		value string
	}{
		{
			"Scheduled",
			formatPHP(
				summary.TotalScheduled,
			),
		},
		{
			"Paid",
			formatPHP(
				summary.TotalPaid,
			),
		},
		{
			"Unpaid",
			formatPHP(
				summary.TotalUnpaid,
			),
		},
	}

	width := 85.0
	height := 20.0
	gap := 8.0

	// IMPORTANT:
	// Capture Y ONCE so every card uses
	// exactly the same vertical position.
	startY := pdf.GetY()

	for i, item := range items {

		x := 10 +
			float64(i)*
				(width+gap)

		// ========================================
		// CARD
		// ========================================

		pdf.Rect(
			x,
			startY,
			width,
			height,
			"",
		)

		// ========================================
		// TITLE
		// ========================================

		pdf.SetXY(
			x,
			startY+3,
		)

		pdf.SetFont(
			"Arial",
			"",
			8,
		)

		pdf.CellFormat(
			width,
			5,
			item.title,
			"",
			0,
			"C",
			false,
			0,
			"",
		)

		// ========================================
		// VALUE
		// ========================================

		pdf.SetXY(
			x,
			startY+10,
		)

		pdf.SetFont(
			"Arial",
			"B",
			11,
		)

		pdf.CellFormat(
			width,
			6,
			item.value,
			"",
			0,
			"C",
			false,
			0,
			"",
		)
	}

	// Move cursor BELOW the cards.
	pdf.SetY(
		startY +
			height +
			5,
	)
}

func drawAmortizationTable(
	pdf *gofpdf.Fpdf,
	rows []dto.AmortizationReportRow,
	summary dto.AmortizationReportSummary,
) {

	pdf.SetFont(
		"Arial",
		"B",
		11,
	)

	pdf.CellFormat(
		0,
		7,
		"AMORTIZATION SCHEDULE",
		"",
		1,
		"L",
		false,
		0,
		"",
	)

	pdf.Ln(2)

	headers := []string{
		"#",
		"Due Date",
		"Principal",
		"Interest",
		"Scheduled",
		"Paid",
		"Unpaid",
		"Status",
	}

	widths := []float64{
		12,
		30,
		35,
		35,
		35,
		35,
		35,
		35,
	}

	drawHeader := func() {

		pdf.SetFont(
			"Arial",
			"B",
			7,
		)

		for i, header := range headers {

			pdf.CellFormat(
				widths[i],
				8,
				header,
				"1",
				0,
				"C",
				false,
				0,
				"",
			)
		}

		pdf.Ln(-1)
	}

	drawHeader()

	pdf.SetFont(
		"Arial",
		"",
		7,
	)

	for _, row := range rows {

		values := []string{
			fmt.Sprintf(
				"%d",
				row.ScheduleNo,
			),
			row.DueDate,
			formatPHP(
				row.ScheduledPrincipal,
			),
			formatPHP(
				row.ScheduledInterest,
			),
			formatPHP(
				row.ScheduledTotal,
			),
			formatPHP(
				row.PaidTotal,
			),
			formatPHP(
				row.UnpaidTotal,
			),
			row.ScheduleStatus,
		}

		for i, value := range values {

			align := "L"

			if i == 0 {
				align = "C"
			}

			if i >= 2 && i <= 6 {
				align = "R"
			}

			if i == 7 {
				align = "C"
			}

			pdf.CellFormat(
				widths[i],
				7,
				value,
				"1",
				0,
				align,
				false,
				0,
				"",
			)
		}

		pdf.Ln(-1)
	}

	// ========================================
	// TOTAL
	// ========================================

	pdf.SetFont(
		"Arial",
		"B",
		7,
	)

	pdf.CellFormat(
		widths[0]+widths[1],
		8,
		"TOTAL",
		"1",
		0,
		"R",
		false,
		0,
		"",
	)

	pdf.CellFormat(
		widths[2],
		8,
		formatPHP(
			summary.TotalScheduledPrincipal,
		),
		"1",
		0,
		"R",
		false,
		0,
		"",
	)

	pdf.CellFormat(
		widths[3],
		8,
		formatPHP(
			summary.TotalScheduledInterest,
		),
		"1",
		0,
		"R",
		false,
		0,
		"",
	)

	pdf.CellFormat(
		widths[4],
		8,
		formatPHP(
			summary.TotalScheduled,
		),
		"1",
		0,
		"R",
		false,
		0,
		"",
	)

	pdf.CellFormat(
		widths[5],
		8,
		formatPHP(
			summary.TotalPaid,
		),
		"1",
		0,
		"R",
		false,
		0,
		"",
	)

	pdf.CellFormat(
		widths[6],
		8,
		formatPHP(
			summary.TotalUnpaid,
		),
		"1",
		0,
		"R",
		false,
		0,
		"",
	)

	pdf.CellFormat(
		widths[7],
		8,
		"",
		"1",
		0,
		"C",
		false,
		0,
		"",
	)
}

// ========================================
// PORTFOLIO AT RISK PDF
// ========================================

func (s *ReportPDFService) GeneratePARReport(
	data *dto.PARReportData,
) (string, error) {

	if data == nil {
		return "", fmt.Errorf(
			"PAR report data is nil",
		)
	}

	if err := os.MkdirAll(
		s.outputDirectory,
		0755,
	); err != nil {
		return "", err
	}

	pdf := gofpdf.New(
		"L",
		"mm",
		"A4",
		"",
	)

	pdf.SetTitle(
		"Portfolio at Risk Report",
		true,
	)

	pdf.SetAuthor(
		"FGC",
		true,
	)

	pdf.SetMargins(
		10,
		10,
		10,
	)

	pdf.SetAutoPageBreak(
		true,
		15,
	)

	pdf.SetFooterFunc(
		func() {

			pdf.SetY(-12)

			pdf.SetFont(
				"Arial",
				"",
				7,
			)

			pdf.CellFormat(
				0,
				5,
				"Generated by FGC",
				"",
				0,
				"L",
				false,
				0,
				"",
			)

			pdf.CellFormat(
				0,
				5,
				fmt.Sprintf(
					"Page %d",
					pdf.PageNo(),
				),
				"",
				0,
				"R",
				false,
				0,
				"",
			)
		},
	)

	// ========================================
	// PAGE 1
	// ========================================

	pdf.AddPage()

	drawPARHeader(pdf)

	drawPARSummary(
		pdf,
		data.Summary,
	)

	drawPARAgingSummary(
		pdf,
		data.Summary,
	)

	// ========================================
	// PAGE 2+
	// ========================================

	pdf.AddPage()

	drawPARTable(
		pdf,
		data.Rows,
	)

	filename := fmt.Sprintf(
		"portfolio_at_risk_%s.pdf",
		time.Now().Format(
			"20060102_150405",
		),
	)

	path := filepath.Join(
		s.outputDirectory,
		filename,
	)

	if err := pdf.OutputFileAndClose(
		path,
	); err != nil {
		return "", err
	}

	return path, nil
}

func drawPARHeader(
	pdf *gofpdf.Fpdf,
) {

	pdf.SetFont(
		"Arial",
		"B",
		18,
	)

	pdf.CellFormat(
		0,
		8,
		"FGC",
		"",
		1,
		"C",
		false,
		0,
		"",
	)

	pdf.SetFont(
		"Arial",
		"B",
		14,
	)

	pdf.CellFormat(
		0,
		8,
		"PORTFOLIO AT RISK REPORT",
		"",
		1,
		"C",
		false,
		0,
		"",
	)

	pdf.SetFont(
		"Arial",
		"",
		9,
	)

	pdf.CellFormat(
		0,
		6,
		fmt.Sprintf(
			"Generated: %s",
			time.Now().Format(
				"January 02, 2006 03:04 PM",
			),
		),
		"",
		1,
		"C",
		false,
		0,
		"",
	)

	pdf.Ln(4)

	pdf.Line(
		10,
		pdf.GetY(),
		287,
		pdf.GetY(),
	)

	pdf.Ln(5)
}

func drawPARSummary(
	pdf *gofpdf.Fpdf,
	summary dto.PARReportSummary,
) {

	pdf.SetFont(
		"Arial",
		"B",
		10,
	)

	pdf.CellFormat(
		0,
		7,
		"PORTFOLIO AT RISK SUMMARY",
		"",
		1,
		"L",
		false,
		0,
		"",
	)

	pdf.Ln(2)

	items := []struct {
		title string
		value string
	}{
		{
			"PAR Loans",
			fmt.Sprintf(
				"%d",
				summary.TotalLoans,
			),
		},
		{
			"Default Amount",
			formatPHP(
				summary.DefaultAmount,
			),
		},
		{
			"Loans at Risk",
			fmt.Sprintf(
				"%d",
				summary.TotalLoans,
			),
		},
	}

	width := 85.0
	height := 22.0
	gap := 8.0

	startY := pdf.GetY()

	for i, item := range items {

		x := 10 +
			float64(i)*
				(width+gap)

		pdf.Rect(
			x,
			startY,
			width,
			height,
			"D",
		)

		pdf.SetXY(
			x,
			startY+4,
		)

		pdf.SetFont(
			"Arial",
			"",
			8,
		)

		pdf.CellFormat(
			width,
			5,
			item.title,
			"",
			0,
			"C",
			false,
			0,
			"",
		)

		pdf.SetXY(
			x,
			startY+11,
		)

		pdf.SetFont(
			"Arial",
			"B",
			12,
		)

		pdf.CellFormat(
			width,
			6,
			item.value,
			"",
			0,
			"C",
			false,
			0,
			"",
		)
	}

	pdf.SetY(
		startY +
			height +
			7,
	)
}

func drawPARAgingSummary(
	pdf *gofpdf.Fpdf,
	summary dto.PARReportSummary,
) {

	pdf.SetFont(
		"Arial",
		"B",
		10,
	)

	pdf.CellFormat(
		0,
		7,
		"AGING BREAKDOWN",
		"",
		1,
		"L",
		false,
		0,
		"",
	)

	pdf.Ln(2)

	items := []struct {
		title  string
		loans  int
		amount float64
	}{
		{
			"1–30 Days",
			summary.Aging1To30Loans,
			summary.Aging1To30Amount,
		},
		{
			"31–60 Days",
			summary.Aging31To60Loans,
			summary.Aging31To60Amount,
		},
		{
			"61–90 Days",
			summary.Aging61To90Loans,
			summary.Aging61To90Amount,
		},
		{
			"90+ Days",
			summary.Aging90PlusLoans,
			summary.Aging90PlusAmount,
		},
	}

	width := 65.0
	height := 32.0
	gap := 6.0

	startY := pdf.GetY()

	for i, item := range items {

		x := 10 +
			float64(i)*
				(width+gap)

		pdf.Rect(
			x,
			startY,
			width,
			height,
			"D",
		)

		// Title
		pdf.SetXY(
			x,
			startY+4,
		)

		pdf.SetFont(
			"Arial",
			"B",
			8,
		)

		pdf.CellFormat(
			width,
			5,
			item.title,
			"",
			0,
			"C",
			false,
			0,
			"",
		)

		// Loan count
		pdf.SetXY(
			x,
			startY+12,
		)

		pdf.SetFont(
			"Arial",
			"B",
			11,
		)

		pdf.CellFormat(
			width,
			6,
			fmt.Sprintf(
				"%d loans",
				item.loans,
			),
			"",
			0,
			"C",
			false,
			0,
			"",
		)

		// Amount
		pdf.SetXY(
			x,
			startY+21,
		)

		pdf.SetFont(
			"Arial",
			"",
			8,
		)

		pdf.CellFormat(
			width,
			5,
			formatPHP(
				item.amount,
			),
			"",
			0,
			"C",
			false,
			0,
			"",
		)
	}

	pdf.SetY(
		startY +
			height +
			8,
	)

	// Explanation
	pdf.SetFont(
		"Arial",
		"",
		8,
	)

	pdf.MultiCell(
		0,
		5,
		"A loan is included in Portfolio at Risk when it has an unpaid scheduled amount past its due date. Advanced payments that fully cover scheduled dues are excluded.",
		"",
		"L",
		false,
	)

	pdf.Ln(3)
}

func drawPARTable(
	pdf *gofpdf.Fpdf,
	rows []dto.PARReportRow,
) {

	pdf.SetFont(
		"Arial",
		"B",
		11,
	)

	pdf.CellFormat(
		0,
		7,
		"PAR LOAN DETAILS",
		"",
		1,
		"L",
		false,
		0,
		"",
	)

	pdf.Ln(2)

	headers := []string{
		"PN Number",
		"Client",
		"Due Date",
		"Days Past Due",
		"Aging",
		"Principal",
		"PN Value",
		"Default Amount",
		"Status",
	}

	widths := []float64{
		27,
		42,
		25,
		25,
		22,
		32,
		32,
		38,
		24,
	}

	drawHeader := func() {

		pdf.SetFont(
			"Arial",
			"B",
			6.5,
		)

		for i, header := range headers {

			pdf.CellFormat(
				widths[i],
				8,
				header,
				"1",
				0,
				"C",
				false,
				0,
				"",
			)
		}

		pdf.Ln(-1)
	}

	drawHeader()

	pdf.SetFont(
		"Arial",
		"",
		6.5,
	)

	for _, row := range rows {

		values := []string{
			row.PNNumber,
			row.ClientName,
			row.OldestDueDate,
			fmt.Sprintf(
				"%d",
				row.DaysPastDue,
			),
			row.AgingBucket,
			formatPHP(
				row.PrincipalAmount,
			),
			formatPHP(
				row.PNValue,
			),
			formatPHP(
				row.DefaultAmount,
			),
			row.LoanStatus,
		}

		for i, value := range values {

			align := "L"

			if i == 2 ||
				i == 3 ||
				i == 4 ||
				i == 8 {

				align = "C"
			}

			if i >= 5 &&
				i <= 7 {

				align = "R"
			}

			pdf.CellFormat(
				widths[i],
				7,
				value,
				"1",
				0,
				align,
				false,
				0,
				"",
			)
		}

		pdf.Ln(-1)
	}

	// ========================================
	// EMPTY STATE
	// ========================================

	if len(rows) == 0 {

		pdf.CellFormat(
			0,
			12,
			"No loans are currently at risk.",
			"1",
			1,
			"C",
			false,
			0,
			"",
		)

		return
	}

	// ========================================
	// TOTAL
	// ========================================

	var totalDefault float64

	for _, row := range rows {
		totalDefault +=
			row.DefaultAmount
	}

	pdf.SetFont(
		"Arial",
		"B",
		7,
	)

	pdf.CellFormat(
		widths[0]+
			widths[1]+
			widths[2]+
			widths[3]+
			widths[4]+
			widths[5]+
			widths[6],
		8,
		"TOTAL",
		"1",
		0,
		"R",
		false,
		0,
		"",
	)

	pdf.CellFormat(
		widths[7],
		8,
		formatPHP(
			totalDefault,
		),
		"1",
		0,
		"R",
		false,
		0,
		"",
	)

	pdf.CellFormat(
		widths[8],
		8,
		"",
		"1",
		0,
		"C",
		false,
		0,
		"",
	)
}

// ========================================
// LOAN PORTFOLIO SUMMARY PDF
// ========================================

func (s *ReportPDFService) GenerateLoanPortfolioReport(
	data *dto.LoanPortfolioReportData,
) (string, error) {

	if data == nil {
		return "", fmt.Errorf(
			"loan portfolio report data is nil",
		)
	}

	if err := os.MkdirAll(
		s.outputDirectory,
		0755,
	); err != nil {
		return "", err
	}

	pdf := gofpdf.New(
		"L",
		"mm",
		"A4",
		"",
	)

	pdf.SetTitle(
		"Loan Portfolio Summary",
		true,
	)

	pdf.SetAuthor(
		"FGC",
		true,
	)

	pdf.SetMargins(
		10,
		10,
		10,
	)

	pdf.SetAutoPageBreak(
		true,
		15,
	)

	pdf.SetFooterFunc(
		func() {

			pdf.SetY(-12)

			pdf.SetFont(
				"Arial",
				"",
				7,
			)

			pdf.CellFormat(
				0,
				5,
				"Generated by FGC",
				"",
				0,
				"L",
				false,
				0,
				"",
			)

			pdf.CellFormat(
				0,
				5,
				fmt.Sprintf(
					"Page %d",
					pdf.PageNo(),
				),
				"",
				0,
				"R",
				false,
				0,
				"",
			)
		},
	)

	// ========================================
	// PAGE 1
	// ========================================

	pdf.AddPage()

	drawLoanPortfolioHeader(pdf)

	drawLoanPortfolioSummary(
		pdf,
		data.Summary,
	)

	drawLoanPortfolioStatus(
		pdf,
		data.Summary,
	)

	drawLoanPortfolioTypes(
		pdf,
		data.Summary,
	)

	// ========================================
	// PAGE 2+
	// ========================================

	pdf.AddPage()

	drawLoanPortfolioTable(
		pdf,
		data.Rows,
	)

	filename := fmt.Sprintf(
		"loan_portfolio_summary_%s.pdf",
		time.Now().Format(
			"20060102_150405",
		),
	)

	path := filepath.Join(
		s.outputDirectory,
		filename,
	)

	if err := pdf.OutputFileAndClose(
		path,
	); err != nil {
		return "", err
	}

	return path, nil
}

func drawLoanPortfolioHeader(
	pdf *gofpdf.Fpdf,
) {

	pdf.SetFont(
		"Arial",
		"B",
		18,
	)

	pdf.CellFormat(
		0,
		8,
		"FGC",
		"",
		1,
		"C",
		false,
		0,
		"",
	)

	pdf.SetFont(
		"Arial",
		"B",
		14,
	)

	pdf.CellFormat(
		0,
		8,
		"LOAN PORTFOLIO SUMMARY",
		"",
		1,
		"C",
		false,
		0,
		"",
	)

	pdf.SetFont(
		"Arial",
		"",
		9,
	)

	pdf.CellFormat(
		0,
		6,
		fmt.Sprintf(
			"Generated: %s",
			time.Now().Format(
				"January 02, 2006 03:04 PM",
			),
		),
		"",
		1,
		"C",
		false,
		0,
		"",
	)

	pdf.Ln(4)

	pdf.Line(
		10,
		pdf.GetY(),
		287,
		pdf.GetY(),
	)

	pdf.Ln(5)
}

func drawLoanPortfolioSummary(
	pdf *gofpdf.Fpdf,
	summary dto.LoanPortfolioReportSummary,
) {

	pdf.SetFont(
		"Arial",
		"B",
		10,
	)

	pdf.CellFormat(
		0,
		7,
		"PORTFOLIO SUMMARY",
		"",
		1,
		"L",
		false,
		0,
		"",
	)

	pdf.Ln(2)

	items := []struct {
		title string
		value string
	}{
		{
			"Total Loans",
			fmt.Sprintf(
				"%d",
				summary.TotalLoans,
			),
		},
		{
			"Total Principal",
			formatPHP(
				summary.TotalPrincipal,
			),
		},
		{
			"Total PN Value",
			formatPHP(
				summary.TotalPNValue,
			),
		},
		{
			"Total Paid",
			formatPHP(
				summary.TotalPaid,
			),
		},
		{
			"Outstanding",
			formatPHP(
				summary.TotalOutstanding,
			),
		},
		{
			"Active Loans",
			fmt.Sprintf(
				"%d",
				summary.ActiveLoans,
			),
		},
	}

	width := 85.0
	height := 21.0
	gap := 8.0

	startX := 10.0
	startY := pdf.GetY()

	for i, item := range items {

		row := i / 3
		col := i % 3

		x := startX +
			float64(col)*
				(width+gap)

		y := startY +
			float64(row)*
				(height+6)

		pdf.Rect(
			x,
			y,
			width,
			height,
			"",
		)

		pdf.SetXY(
			x,
			y+4,
		)

		pdf.SetFont(
			"Arial",
			"",
			8,
		)

		pdf.CellFormat(
			width,
			5,
			item.title,
			"",
			0,
			"C",
			false,
			0,
			"",
		)

		pdf.SetXY(
			x,
			y+11,
		)

		pdf.SetFont(
			"Arial",
			"B",
			11,
		)

		pdf.CellFormat(
			width,
			6,
			item.value,
			"",
			0,
			"C",
			false,
			0,
			"",
		)
	}

	pdf.SetY(
		startY +
			(2 * (height + 6)) +
			5,
	)
}

func drawLoanPortfolioStatus(
	pdf *gofpdf.Fpdf,
	summary dto.LoanPortfolioReportSummary,
) {

	pdf.SetFont(
		"Arial",
		"B",
		10,
	)

	pdf.CellFormat(
		0,
		7,
		"LOAN STATUS BREAKDOWN",
		"",
		1,
		"L",
		false,
		0,
		"",
	)

	pdf.Ln(2)

	headers := []string{
		"Status",
		"Loans",
		"Principal",
		"Outstanding",
	}

	widths := []float64{
		65,
		35,
		75,
		75,
	}

	pdf.SetFont(
		"Arial",
		"B",
		7,
	)

	for i, header := range headers {

		pdf.CellFormat(
			widths[i],
			8,
			header,
			"1",
			0,
			"C",
			false,
			0,
			"",
		)
	}

	pdf.Ln(-1)

	pdf.SetFont(
		"Arial",
		"",
		7,
	)

	for _, item := range summary.StatusBreakdown {

		pdf.CellFormat(
			widths[0],
			7,
			item.Status,
			"1",
			0,
			"L",
			false,
			0,
			"",
		)

		pdf.CellFormat(
			widths[1],
			7,
			fmt.Sprintf(
				"%d",
				item.Loans,
			),
			"1",
			0,
			"C",
			false,
			0,
			"",
		)

		pdf.CellFormat(
			widths[2],
			7,
			formatPHP(
				item.Principal,
			),
			"1",
			0,
			"R",
			false,
			0,
			"",
		)

		pdf.CellFormat(
			widths[3],
			7,
			formatPHP(
				item.Outstanding,
			),
			"1",
			0,
			"R",
			false,
			0,
			"",
		)

		pdf.Ln(-1)
	}

	pdf.Ln(5)
}
func drawLoanPortfolioTypes(
	pdf *gofpdf.Fpdf,
	summary dto.LoanPortfolioReportSummary,
) {

	pdf.SetFont(
		"Arial",
		"B",
		10,
	)

	pdf.CellFormat(
		0,
		7,
		"LOAN TYPE BREAKDOWN",
		"",
		1,
		"L",
		false,
		0,
		"",
	)

	pdf.Ln(2)

	headers := []string{
		"Loan Type",
		"Loans",
		"Principal",
		"Outstanding",
	}

	widths := []float64{
		65,
		35,
		75,
		75,
	}

	pdf.SetFont(
		"Arial",
		"B",
		7,
	)

	for i, header := range headers {

		pdf.CellFormat(
			widths[i],
			8,
			header,
			"1",
			0,
			"C",
			false,
			0,
			"",
		)
	}

	pdf.Ln(-1)

	pdf.SetFont(
		"Arial",
		"",
		7,
	)

	for _, item := range summary.TypeBreakdown {

		pdf.CellFormat(
			widths[0],
			7,
			item.LoanType,
			"1",
			0,
			"L",
			false,
			0,
			"",
		)

		pdf.CellFormat(
			widths[1],
			7,
			fmt.Sprintf(
				"%d",
				item.Loans,
			),
			"1",
			0,
			"C",
			false,
			0,
			"",
		)

		pdf.CellFormat(
			widths[2],
			7,
			formatPHP(
				item.Principal,
			),
			"1",
			0,
			"R",
			false,
			0,
			"",
		)

		pdf.CellFormat(
			widths[3],
			7,
			formatPHP(
				item.Outstanding,
			),
			"1",
			0,
			"R",
			false,
			0,
			"",
		)

		pdf.Ln(-1)
	}
}

func drawLoanPortfolioTable(
	pdf *gofpdf.Fpdf,
	rows []dto.LoanPortfolioReportRow,
) {

	pdf.SetFont(
		"Arial",
		"B",
		11,
	)

	pdf.CellFormat(
		0,
		7,
		"LOAN PORTFOLIO DETAILS",
		"",
		1,
		"L",
		false,
		0,
		"",
	)

	pdf.Ln(2)

	headers := []string{
		"PN Number",
		"Client",
		"Type",
		"Principal",
		"PN Value",
		"Outstanding",
		"Rate",
		"Term",
		"Frequency",
		"Status",
	}

	widths := []float64{
		24,
		39,
		25,
		32,
		32,
		36,
		20,
		16,
		23,
		20,
	}

	drawHeader := func() {

		pdf.SetFont(
			"Arial",
			"B",
			6.2,
		)

		for i, header := range headers {

			pdf.CellFormat(
				widths[i],
				8,
				header,
				"1",
				0,
				"C",
				false,
				0,
				"",
			)
		}

		pdf.Ln(-1)
	}

	drawHeader()

	pdf.SetFont(
		"Arial",
		"",
		6.2,
	)

	for _, row := range rows {

		values := []string{
			row.PNNumber,
			row.ClientName,
			row.LoanType,
			formatPHP(
				row.PrincipalAmount,
			),
			formatPHP(
				row.PNValue,
			),
			formatPHP(
				row.OutstandingAmount,
			),
			fmt.Sprintf(
				"%.2f%%",
				row.InterestRate,
			),
			fmt.Sprintf(
				"%d",
				row.LoanTerm,
			),
			row.Frequency,
			row.LoanStatus,
		}

		for i, value := range values {

			align := "L"

			if i >= 3 &&
				i <= 7 {
				align = "R"
			}

			if i == 8 ||
				i == 9 {
				align = "C"
			}

			pdf.CellFormat(
				widths[i],
				7,
				value,
				"1",
				0,
				align,
				false,
				0,
				"",
			)
		}

		pdf.Ln(-1)
	}

	if len(rows) == 0 {

		pdf.CellFormat(
			0,
			12,
			"No loans found in the portfolio.",
			"1",
			1,
			"C",
			false,
			0,
			"",
		)
	}
}

// ========================================
// LOAN MATURITY / DUE PDF
// ========================================

func (s *ReportPDFService) GenerateLoanMaturityReport(
	data *dto.LoanMaturityReportData,
) (string, error) {

	if data == nil {
		return "", fmt.Errorf(
			"loan maturity report data is nil",
		)
	}

	if err := os.MkdirAll(
		s.outputDirectory,
		0755,
	); err != nil {
		return "", err
	}

	pdf := gofpdf.New(
		"L",
		"mm",
		"A4",
		"",
	)

	pdf.SetTitle(
		"Loan Maturity and Due Report",
		true,
	)

	pdf.SetAuthor(
		"FGC",
		true,
	)

	pdf.SetMargins(
		10,
		10,
		10,
	)

	pdf.SetAutoPageBreak(
		true,
		15,
	)

	pdf.SetFooterFunc(
		func() {

			pdf.SetY(-12)

			pdf.SetFont(
				"Arial",
				"",
				7,
			)

			pdf.CellFormat(
				0,
				5,
				"Generated by FGC",
				"",
				0,
				"L",
				false,
				0,
				"",
			)

			pdf.CellFormat(
				0,
				5,
				fmt.Sprintf(
					"Page %d",
					pdf.PageNo(),
				),
				"",
				0,
				"R",
				false,
				0,
				"",
			)
		},
	)

	// ========================================
	// PAGE 1
	// ========================================

	pdf.AddPage()

	drawLoanMaturityHeader(pdf)

	drawLoanMaturitySummary(
		pdf,
		data.Summary,
	)

	drawLoanMaturityBuckets(
		pdf,
		data.Summary,
	)

	// ========================================
	// PAGE 2+
	// ========================================

	pdf.AddPage()

	drawLoanMaturityTable(
		pdf,
		data.Rows,
	)

	filename := fmt.Sprintf(
		"loan_maturity_due_%s.pdf",
		time.Now().Format(
			"20060102_150405",
		),
	)

	path := filepath.Join(
		s.outputDirectory,
		filename,
	)

	if err := pdf.OutputFileAndClose(
		path,
	); err != nil {
		return "", err
	}

	return path, nil
}

func drawLoanMaturityHeader(
	pdf *gofpdf.Fpdf,
) {

	pdf.SetFont(
		"Arial",
		"B",
		18,
	)

	pdf.CellFormat(
		0,
		8,
		"FGC",
		"",
		1,
		"C",
		false,
		0,
		"",
	)

	pdf.SetFont(
		"Arial",
		"B",
		14,
	)

	pdf.CellFormat(
		0,
		8,
		"LOAN MATURITY AND DUE REPORT",
		"",
		1,
		"C",
		false,
		0,
		"",
	)

	pdf.SetFont(
		"Arial",
		"",
		9,
	)

	pdf.CellFormat(
		0,
		6,
		fmt.Sprintf(
			"Generated: %s",
			time.Now().Format(
				"January 02, 2006 03:04 PM",
			),
		),
		"",
		1,
		"C",
		false,
		0,
		"",
	)

	pdf.Ln(4)

	pdf.Line(
		10,
		pdf.GetY(),
		287,
		pdf.GetY(),
	)

	pdf.Ln(5)
}

func drawLoanMaturitySummary(
	pdf *gofpdf.Fpdf,
	summary dto.LoanMaturityReportSummary,
) {

	pdf.SetFont(
		"Arial",
		"B",
		10,
	)

	pdf.CellFormat(
		0,
		7,
		"MATURITY SUMMARY",
		"",
		1,
		"L",
		false,
		0,
		"",
	)

	pdf.Ln(2)

	items := []struct {
		title string
		value string
	}{
		{
			"Total Loans",
			fmt.Sprintf(
				"%d",
				summary.TotalLoans,
			),
		},
		{
			"Total Outstanding",
			formatPHP(
				summary.TotalOutstanding,
			),
		},
		{
			"Matured Loans",
			fmt.Sprintf(
				"%d",
				summary.MaturedLoans,
			),
		},
		{
			"Matured Amount",
			formatPHP(
				summary.MaturedAmount,
			),
		},
		{
			"Due Today",
			fmt.Sprintf(
				"%d",
				summary.DueTodayLoans,
			),
		},
		{
			"Upcoming Loans",
			fmt.Sprintf(
				"%d",
				summary.UpcomingLoans,
			),
		},
	}

	width := 85.0
	height := 21.0
	gap := 8.0

	startY := pdf.GetY()

	for i, item := range items {

		row := i / 3
		col := i % 3

		x := 10 +
			float64(col)*
				(width+gap)

		y := startY +
			float64(row)*
				(height+6)

		pdf.Rect(
			x,
			y,
			width,
			height,
			"",
		)

		pdf.SetXY(
			x,
			y+4,
		)

		pdf.SetFont(
			"Arial",
			"",
			8,
		)

		pdf.CellFormat(
			width,
			5,
			item.title,
			"",
			0,
			"C",
			false,
			0,
			"",
		)

		pdf.SetXY(
			x,
			y+11,
		)

		pdf.SetFont(
			"Arial",
			"B",
			11,
		)

		pdf.CellFormat(
			width,
			6,
			item.value,
			"",
			0,
			"C",
			false,
			0,
			"",
		)
	}

	pdf.SetY(
		startY +
			(2 * (height + 6)) +
			5,
	)
}

func drawLoanMaturityBuckets(
	pdf *gofpdf.Fpdf,
	summary dto.LoanMaturityReportSummary,
) {

	pdf.SetFont(
		"Arial",
		"B",
		10,
	)

	pdf.CellFormat(
		0,
		7,
		"MATURITY BREAKDOWN",
		"",
		1,
		"L",
		false,
		0,
		"",
	)

	pdf.Ln(2)

	headers := []string{
		"Maturity Status",
		"Loans",
		"Outstanding",
	}

	widths := []float64{
		95,
		45,
		130,
	}

	pdf.SetFont(
		"Arial",
		"B",
		7,
	)

	for i, header := range headers {

		pdf.CellFormat(
			widths[i],
			8,
			header,
			"1",
			0,
			"C",
			false,
			0,
			"",
		)
	}

	pdf.Ln(-1)

	pdf.SetFont(
		"Arial",
		"",
		7,
	)

	for _, item := range summary.BucketBreakdown {

		pdf.CellFormat(
			widths[0],
			7,
			item.Bucket,
			"1",
			0,
			"L",
			false,
			0,
			"",
		)

		pdf.CellFormat(
			widths[1],
			7,
			fmt.Sprintf(
				"%d",
				item.Loans,
			),
			"1",
			0,
			"C",
			false,
			0,
			"",
		)

		pdf.CellFormat(
			widths[2],
			7,
			formatPHP(
				item.Outstanding,
			),
			"1",
			0,
			"R",
			false,
			0,
			"",
		)

		pdf.Ln(-1)
	}

	pdf.Ln(5)

	pdf.SetFont(
		"Arial",
		"",
		8,
	)

	pdf.MultiCell(
		0,
		5,
		"This report uses the loan maturity date recorded in the loan account. Outstanding amounts are based on unpaid principal and interest from the amortization schedules.",
		"",
		"L",
		false,
	)
}

func drawLoanMaturityTable(
	pdf *gofpdf.Fpdf,
	rows []dto.LoanMaturityReportRow,
) {

	pdf.SetFont(
		"Arial",
		"B",
		11,
	)

	pdf.CellFormat(
		0,
		7,
		"LOAN MATURITY DETAILS",
		"",
		1,
		"L",
		false,
		0,
		"",
	)

	pdf.Ln(2)

	headers := []string{
		"PN Number",
		"Client",
		"Maturity Date",
		"Days",
		"Status",
		"Principal",
		"Outstanding",
		"Loan Status",
	}

	widths := []float64{
		28,
		48,
		30,
		22,
		35,
		38,
		42,
		34,
	}

	drawHeader := func() {

		pdf.SetFont(
			"Arial",
			"B",
			6.5,
		)

		for i, header := range headers {

			pdf.CellFormat(
				widths[i],
				8,
				header,
				"1",
				0,
				"C",
				false,
				0,
				"",
			)
		}

		pdf.Ln(-1)
	}

	drawHeader()

	pdf.SetFont(
		"Arial",
		"",
		6.5,
	)

	for _, row := range rows {

		values := []string{
			row.PNNumber,
			row.ClientName,
			row.MaturityDate,
			fmt.Sprintf(
				"%d",
				row.DaysUntilMaturity,
			),
			row.MaturityStatus,
			formatPHP(
				row.PrincipalAmount,
			),
			formatPHP(
				row.OutstandingAmount,
			),
			row.LoanStatus,
		}

		for i, value := range values {

			align := "L"

			if i == 2 ||
				i == 3 ||
				i == 4 ||
				i == 7 {

				align = "C"
			}

			if i == 5 ||
				i == 6 {

				align = "R"
			}

			pdf.CellFormat(
				widths[i],
				7,
				value,
				"1",
				0,
				align,
				false,
				0,
				"",
			)
		}

		pdf.Ln(-1)
	}

	if len(rows) == 0 {

		pdf.CellFormat(
			0,
			12,
			"No loan maturity records found.",
			"1",
			1,
			"C",
			false,
			0,
			"",
		)
	}
}
